apiVersion: v1
kind: PersistentVolume
metadata:
   name: mariadb-galera-pv-0
spec:
   storageClassName: local-storage 
   capacity:
     storage: 8Gi
   accessModes:
     - ReadWriteOnce
   hostPath:
     path: "/bitnami/mariadb"
---
apiVersion: v1
kind: PersistentVolume
metadata:
   name: mariadb-galera-pv-1
spec:
   storageClassName: local-storage 
   capacity:
     storage: 8Gi
   accessModes:
     - ReadWriteOnce
   hostPath:
     path: "/bitnami/mariadb"
---
---
apiVersion: v1
kind: PersistentVolume
metadata:
   name: mariadb-galera-pv-2
spec:
   storageClassName: local-storage 
   capacity:
     storage: 8Gi
   accessModes:
     - ReadWriteOnce
   hostPath:
     path: "/bitnami/mariadb"
     